// Cloudflare Worker: keeps GitHub token server-side.
// Required secrets: GITHUB_TOKEN, ADMIN_USERNAME, ADMIN_PASSWORD
// Required vars: GITHUB_OWNER, GITHUB_REPO
// Optional vars: GITHUB_BRANCH (default main), DATA_PATH (default data/products.json), ALLOWED_ORIGIN (default *)
const json=(body,status=200,headers={})=>new Response(typeof body==='string'?body:JSON.stringify(body),{status,headers:{'content-type':'application/json;charset=UTF-8',...headers}});
function cors(env){return {'Access-Control-Allow-Origin':env.ALLOWED_ORIGIN||'*','Access-Control-Allow-Headers':'Content-Type, X-Admin-Username, X-Admin-Password','Access-Control-Allow-Methods':'GET, PUT, OPTIONS'}}
function auth(req,env){return req.headers.get('X-Admin-Username')===env.ADMIN_USERNAME&&req.headers.get('X-Admin-Password')===env.ADMIN_PASSWORD}
async function gh(env,path,init={}){const branch=env.GITHUB_BRANCH||'main';const url=`https://api.github.com/repos/${env.GITHUB_OWNER}/${env.GITHUB_REPO}/contents/${path}${init.method?'':`?ref=${encodeURIComponent(branch)}`}`;return fetch(url,{...init,headers:{'Authorization':`Bearer ${env.GITHUB_TOKEN}`,'Accept':'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28','User-Agent':'National-Mobile-Admin',...(init.headers||{})}})}
export default{async fetch(req,env){const h=cors(env);if(req.method==='OPTIONS')return new Response(null,{headers:h});const u=new URL(req.url);if(u.pathname!='/products')return json({error:'Not found'},404,h);if(!auth(req,env))return json({error:'Unauthorized'},401,h);const path=env.DATA_PATH||'data/products.json';if(req.method==='GET'){const r=await gh(env,path);if(!r.ok)return json({error:await r.text()},r.status,h);const f=await r.json();const content=decodeURIComponent(escape(atob(f.content.replace(/\n/g,''))));return new Response(content,{headers:{...h,'content-type':'application/json;charset=UTF-8','Cache-Control':'no-store'}})}if(req.method==='PUT'){let body;try{body=await req.json()}catch{return json({error:'Invalid JSON'},400,h)}if(!body||!Array.isArray(body.products))return json({error:'products array required'},400,h);const current=await gh(env,path);if(!current.ok)return json({error:await current.text()},current.status,h);const meta=await current.json();const encoded=btoa(unescape(encodeURIComponent(JSON.stringify(body,null,2)+'\n')));const branch=env.GITHUB_BRANCH||'main';const r=await gh(env,path,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:`Admin: update price list ${new Date().toISOString()}`,content:encoded,sha:meta.sha,branch})});if(!r.ok)return json({error:await r.text()},r.status,h);const done=await r.json();return json({ok:true,commit:done.commit?.sha},200,h)}return json({error:'Method not allowed'},405,h)}}};
